@Nick_Admin= eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjczMTk2NjZ9.UK4r9ct82br6Fh4RvP2AvrclO7C7_1Wvgg1vgSstJO4
@sam_notadmin= eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjY4ODkxOTF9.wCLQhRk8rBNW8uP1dWz-q7yNIphjvP0aZv3ZQQ3gr3E

get http://localhost:3000/books.json
Content-Type: application/json

{
  
}

###
get http://localhost:3000/books/7.json

###
# Create Books Post for Admin
post http://localhost:3000/books.json
Authorization: Bearer {{Nick_Admin}}
Content-Type: application/json

{
  "title": "Alice in Wonderland",
  "stock": 100,
  "author_id": 1,
  "available": 100,
  "category": "Fiction"
}

###
#Books Update for Admins
PATCH http://localhost:3000/books/3.json
Authorization: Bearer {{sam_notadmin}}
Content-Type: application/json

{
  "stock": 100,
  "author_id": 1,
  "available": 3,
  "title": "A Good Man is Hard To Find"
}


###
#Delete for Admins
DELETE http://localhost:3000/books/5.json
Authorization: Bearer {{Nick_Admin}}





###
get http://localhost:3000/categories.json


###
post http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Sam",
  "email": "sam@sam.com",
  "password": "password",
  "authority": false
}


###
post http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "nick@nick.com",
  "password":"password"
}

### show books in cart. uses body params - cart?, rented?, or previous?
get http://localhost:3000/rented_books.json
Content-Type: application/json
Authorization: Bearer {{Nick_Admin}}

{
  "book_id": 1, 
  "cart?": true
}

###
DELETE http://localhost:3000/rented_books/1.json
Authorization: Bearer 

###
# Add books to cart
post http://localhost:3000/rented_books.json
Content-Type: application/json
Authorization: Bearer {{Nick_Admin}}

{
  "book_id": 3
}

###
post http://localhost:3000/rentals.json
Authorization: Bearer 

###




