@admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjY4MTQ3NjV9.V6LjO9tMpuBK8hDa7priNZ30QW30tLA5yy3AZPuVIlA

@NotAdmin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjY4MTQ4ODJ9.dLfscnWZ51fnLVfYGPV6rlKJXpNHra4xlbVnzLx7AZk

get http://localhost:3000/books.json
Content-Type: application/json

{
  "category": "Fantasy"
}

###
get http://localhost:3000/books/2.json

###
# Books Post for Admin
post http://localhost:3000/books.json
Authorization: Bearer {{admin}}
Content-Type: application/json

{
  "title": "Lost at Sea",
  "stock": 100,
  "author_id": 1,
  "available": 100
}



###
get http://localhost:3000/categories.json


###
post http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Sam",
  "email": "sam@sam.com",
  "password": "password",
  "authority": false
}


###
post http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "sam@sam.com",
  "password":"password"
}

### show books in cart. URL will be changes to /cart
get http://localhost:3000/rented_books.json
Content-Type: application/json
Authorization: Bearer {{user}}

{
  "book_id": 1,
  "cart?": true
}

###
DELETE http://localhost:3000/rented_books/1.json
Authorization: Bearer {{user}}

###
post http://localhost:3000/rented_books.json
Content-Type: application/json
Authorization: Bearer {{user}}

{
  "book_id": 1
}

###
post http://localhost:3000/rentals.json
Authorization: Bearer {{user}}

###




