@user = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjA1MTQ1NjR9.CwL0GDADtfmFBOhg5_Ou6bDQiAgXGXmSANN24qlsJX8

get http://localhost:3000/books.json
Content-Type: application/json

{
  "category": "Fantasy"
}

###
get http://localhost:3000/books/3.json


###
get http://localhost:3000/categories.json


###
post http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Nick Williams",
  "email": "nick@nick.com",
  "password": "password",
  "authority": 0
}


###
post http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "john@john.com",
  "password": "password"
}

### show books in cart. URL will be changes to /cart
get http://localhost:3000/rented_books.json
Content-Type: application/json
Authorization: Bearer {{user}}

{
  "rentals?": true
}

###
DELETE http://localhost:3000/rented_books/1.json
Authorization: Bearer {{user}}

###
post http://localhost:3000/rented_books.json
Content-Type: application/json
Authorization: Bearer {{user}}

{
  "book_id": 3
}

###
post http://localhost:3000/rentals.json
Authorization: Bearer {{user}}


###


